local utils = require("ebeau.core.utils")

-- trivial plugins without config nor dependency
utils.enable_lazy_plugin("christoomey/vim-tmux-navigator")
utils.enable_lazy_plugin("nvim-lua/plenary.nvim")
utils.enable_lazy_plugin("inkarkat/vim-ReplaceWithRegister")
utils.enable_lazy_plugin("tpope/vim-dispatch")

-- plugins with configuration
utils.enable_lazy_plugin("ebeau.plugins.alpha-nvim")
utils.enable_lazy_plugin("ebeau.plugins.bufdel")
utils.enable_lazy_plugin("ebeau.plugins.bufferline")
utils.enable_lazy_plugin("ebeau.plugins.colorscheme")
utils.enable_lazy_plugin("ebeau.plugins.comment")
utils.enable_lazy_plugin("ebeau.plugins.cppman")
utils.enable_lazy_plugin("ebeau.plugins.dressing")
utils.enable_lazy_plugin("ebeau.plugins.exrc")
utils.enable_lazy_plugin("ebeau.plugins.harpoon")
utils.enable_lazy_plugin("ebeau.plugins.impatient")
utils.enable_lazy_plugin("ebeau.plugins.indent")
utils.enable_lazy_plugin("ebeau.plugins.lsp")
utils.enable_lazy_plugin("ebeau.plugins.nvim-dap")
utils.enable_lazy_plugin("ebeau.plugins.lualine")
utils.enable_lazy_plugin("ebeau.plugins.marks")
utils.enable_lazy_plugin("ebeau.plugins.mvim-web-devicons")
utils.enable_lazy_plugin("ebeau.plugins.nvim-autopairs")
utils.enable_lazy_plugin("ebeau.plugins.nvim-cmp")
utils.enable_lazy_plugin("ebeau.plugins.nvim-colorizer")
utils.enable_lazy_plugin("ebeau.plugins.nvim-surround")
utils.enable_lazy_plugin("ebeau.plugins.nvim-tree")
utils.enable_lazy_plugin("ebeau.plugins.nvim-tresitter")
utils.enable_lazy_plugin("ebeau.plugins.nvim-ufo")
utils.enable_lazy_plugin("ebeau.plugins.telescope")
utils.enable_lazy_plugin("ebeau.plugins.vim-maximizer")
utils.enable_lazy_plugin("ebeau.plugins.vim-treesitter-text-objects")
utils.enable_lazy_plugin("ebeau.plugins.workspaces")
utils.enable_lazy_plugin("ebeau.plugins.eyeliner")
utils.enable_lazy_plugin("ebeau.plugins.bigfile")


-- deactivated  plugins
-- utils.enable_lazy_plugin("ebeau.plugins.illuminate")
-- utils.enable_lazy_plugin("ebeau.plugins.bqf")
